# Generated by Django 3.0.6 on 2020-06-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('blogs', '0009_auto_20200603_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPage',
        ),
    ]
