# Generated by Django 3.0.6 on 2020-06-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_delete_postpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='description',
        ),
    ]
