# Generated by Django 2.1 on 2019-07-11 02:03

from django.db import migrations, models
import django.db.models.deletion
import inicio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album_fotos_variadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Boda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(max_length=20)),
                ('nombre_novia', models.CharField(max_length=50)),
                ('nombre_novio', models.CharField(max_length=50)),
                ('localizacion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Bodas',
                'ordering': ('fecha_realizacion',),
            },
        ),
        migrations.CreateModel(
            name='Foto_carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='')),
                ('boda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Boda')),
            ],
            options={
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Fotos_de_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boda', models.CharField(max_length=30)),
                ('foto', models.ImageField(null=None, upload_to='')),
                ('fotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Album_fotos_variadas')),
            ],
        ),
        migrations.CreateModel(
            name='fotos_portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_reducida', models.ImageField(upload_to='')),
                ('imagen_grande', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(blank=True, default='Foto', help_text='Ingrese una breve descripción opcional', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('testimonio', models.TextField(max_length=150)),
                ('foto', models.ImageField(upload_to='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('estrellas', models.IntegerField(default=5, validators=[inicio.models.validar_calificacion])),
            ],
            options={
                'verbose_name_plural': 'Testimonios',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
