# Generated by Django 2.1 on 2019-07-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto1',
        ),
        migrations.AlterField(
            model_name='fotos',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='', width_field=5),
        ),
    ]
