# Generated by Django 3.0.6 on 2020-06-02 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200531_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 15, 1, 47, 181675, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
