# Generated by Django 3.0.6 on 2020-06-02 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_categoria_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 19, 10, 59, 717141, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
