# Generated by Django 3.0.6 on 2020-06-03 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200602_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 11, 41, 28, 303018, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
