# Generated by Django 3.0.6 on 2020-06-03 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200603_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 17, 55, 35, 709417, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
