# Generated by Django 3.0.6 on 2020-06-03 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20200603_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 18, 10, 3, 800571, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
