# Generated by Django 3.0.6 on 2020-06-06 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200603_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 11, 40, 29, 170157, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
