# Generated by Django 2.1 on 2019-04-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(max_length=20)),
                ('nombre_novia', models.CharField(max_length=50)),
                ('nombre_novio', models.CharField(max_length=50)),
                ('localizacion', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('fecha_realizacion',),
            },
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='foto')),
                ('boda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Boda')),
            ],
        ),
    ]
