# Generated by Django 2.1 on 2019-04-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20190419_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_fotos_variadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto6', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto7', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto8', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto9', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto10', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto11', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto12', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto13', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto14', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto15', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto16', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto17', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto18', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto19', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto20', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
