# Generated by Django 2.1 on 2019-04-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_album_fotos_variadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
    ]
