# Generated by Django 2.1 on 2019-04-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_foto_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_carrusel',
            name='descripcion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
