# Generated by Django 2.1 on 2019-04-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20190419_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto10',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto11',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto12',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto13',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto14',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto15',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto16',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto17',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto18',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto19',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto20',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto3',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto4',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto5',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto6',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto7',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto8',
        ),
        migrations.RemoveField(
            model_name='album_fotos_variadas',
            name='foto9',
        ),
    ]
