# Generated by Django 2.1 on 2019-04-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20190419_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_fotos_variadas',
            name='nombre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
