# Generated by Django 2.1 on 2019-04-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20190424_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boda',
            options={'ordering': ('fecha_realizacion',), 'verbose_name_plural': 'Bodas'},
        ),
        migrations.AlterModelOptions(
            name='fotos',
            options={'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterModelOptions(
            name='testimonio',
            options={'ordering': ['fecha_creacion'], 'verbose_name_plural': 'Testimonios'},
        ),
    ]
