# Generated by Django 2.1 on 2019-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_auto_20190424_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='testimonio',
            field=models.TextField(max_length=150),
        ),
    ]
