# Generated by Django 2.1 on 2019-04-24 19:41

from django.db import migrations, models
import inicio.models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_auto_20190424_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='estrellas',
            field=models.IntegerField(default=5, validators=[inicio.models.validar_calificacion]),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='profesion',
            field=models.CharField(blank=None, max_length=20, null=True),
        ),
    ]
