# Generated by Django 2.1 on 2019-04-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_auto_20190424_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='profesion',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
